"""Interfaces the application needs from the outside world.

Infrastructure provides the implementations; the application only ever
depends on these protocols.
"""
from __future__ import annotations

from datetime import date, datetime
from pathlib import Path
from typing import Protocol

from ..domain import Course, Event, Note, Task


class CourseRepository(Protocol):
    def list(self) -> list[Course]: ...
    def get(self, course_id: int) -> Course | None: ...
    def add(self, course: Course) -> int: ...
    def update(self, course: Course) -> None: ...
    def delete(self, course_id: int) -> None: ...


class EventRepository(Protocol):
    def between(self, first: date, last: date) -> list[Event]: ...
    def get(self, event_id: int) -> Event | None: ...
    def add(self, event: Event) -> int: ...
    def update(self, event: Event) -> None: ...
    def delete(self, event_id: int) -> None: ...


class TaskRepository(Protocol):
    def list(self, include_done: bool = True, course_id: int | None = None) -> list[Task]: ...
    def due_on(self, day: date) -> list[Task]: ...
    def open_due_before(self, day: date) -> list[Task]: ...
    def get(self, task_id: int) -> Task | None: ...
    def add(self, task: Task) -> int: ...
    def update(self, task: Task) -> None: ...
    def delete(self, task_id: int) -> None: ...


class NoteRepository(Protocol):
    def search(self, text: str = "", course_id: int | None = None) -> list[Note]: ...
    def find_by_title(self, title: str, course_id: int | None) -> Note | None: ...
    def get(self, note_id: int) -> Note | None: ...
    def add(self, note: Note) -> int: ...
    def update(self, note: Note) -> None: ...
    def delete(self, note_id: int) -> None: ...


class JournalRepository(Protocol):
    def get(self, day: date) -> str: ...
    def put(self, day: date, body: str) -> None: ...


class Storage(Protocol):
    @property
    def location(self) -> Path: ...
    def backup_to(self, dest: Path) -> None: ...


class Clock(Protocol):
    def today(self) -> date: ...
    def now(self) -> datetime: ...
